### ISSUE TITLE
Jetson nano?

### ISSUE THREAD

**Issue by fpgasdr** [deepwavedigital/gr-cuda#2]
Hello,
installed this component in gnuradio 3.7.11 in jetson nano 2G but get syntax error when running example:

Traceback (most recent call last):
File “/home/juli/gnuradio/gr-cuda/test/top_block.py”, line 17, in
import cuda
File “/usr/local/lib/python2.7/dist-packages/cuda/init.py”, line 34, in
from gpu_kernel import gpu_kernel
File “/usr/local/lib/python2.7/dist-packages/cuda/gpu_kernel.py”, line 25, in
import pycuda.compiler
File “/home/juli/.local/lib/python2.7/site-packages/pycuda/compiler.py”, line 3, in
from pytools import memoize
File “/home/juli/.local/lib/python2.7/site-packages/pytools/init.py”, line 249
slots: List[str] = []
^
SyntaxError: invalid syntax

from readme it says the pycuda version used is 9.0 but in jetson nano only from version 10 is available(I have the 10.2).

**Comment by dicta** [comment]
Recent versions of pycuda and pytools have dropped support for Python 2.7 (which is required for GNU Radio 3.7.x). 

You can work around this by pinning your installed versions of pycuda and pytools to released versions that still have 2.7 support. Try running the following command:

```
pip install pycuda==2019.1.2 pytools==2020.1
```

**Comment by fpgasdr** [comment]
thanks @dicta  for the support,

After install the pycuda and pytools get a strange error with cupy as not detected(I am almost certainly that was installed).

Anyway, installed cupy with pip2 (pip use python 3) but get the next error:

Traceback (most recent call last):
  File "divide_by_two.py", line 31, in <module>
    import cuda
  File "/usr/local/lib/python2.7/dist-packages/cuda/__init__.py", line 34, in <module>
    from gpu_kernel import gpu_kernel
  File "/usr/local/lib/python2.7/dist-packages/cuda/gpu_kernel.py", line 27, in <module>
    import cupy as cp
  File "/home/juli/.local/lib/python2.7/site-packages/cupy/__init__.py", line 47, in <module>
    import cupyx as _cupyx
  File "/home/juli/.local/lib/python2.7/site-packages/cupyx/__init__.py", line 11, in <module>
    from cupyx._ufunc_config import errstate  # NOQA
  File "/home/juli/.local/lib/python2.7/site-packages/cupyx/_ufunc_config.py", line 52
    def errstate(*, divide=None, over=None, under=None, invalid=None, linalg=None):
                  ^
SyntaxError: invalid syntax


maybe need to install a compatible version of cupy?.
